#!/usr/bin/env node
/**
 * build-deploy.mjs — kompletní deploy pipeline pro v4.0+
 * Datum: 2026-05-12
 *
 * Účel: vygenerovat **dva** separátní buildy a rozdistribuovat je do
 *   - public_html/        (LIVE www.panprstenu.cz, indexovatelné)
 *   - public_html_new/    (NEW preprod new.panprstenu.cz, NOINDEX)
 *
 * Tok:
 *   1) prebuild (translation-status + llms)
 *   2) astro build (default env, BEZ PUBLIC_NOINDEX) → dist/ → public_html/
 *   3) astro build (PUBLIC_NOINDEX=true)              → dist/ → public_html_new/
 *   4) Přepsat public_html_new/robots.txt na "Disallow: /" (preprod nemá co indexovat)
 *
 * Astro `BaseLayout.astro` čte env `PUBLIC_NOINDEX` při buildu a injektuje
 * <meta name="robots" content="noindex, nofollow"> + zakáže GA na všech stránkách.
 *
 * Spuštění:
 *   npm run build     ← výchozí cesta
 *   node scripts/build-deploy.mjs   ← přímé volání
 */

import { rm, cp, stat, readdir, writeFile } from 'node:fs/promises';
import { execSync } from 'node:child_process';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SRC = join(ROOT, 'dist');
const TARGET_LIVE = join(ROOT, 'public_html');
const TARGET_NEW = join(ROOT, 'public_html_new');

const exists = async (p) => {
  try { await stat(p); return true; } catch { return false; }
};

const countFiles = async (dir) => {
  if (!(await exists(dir))) return 0;
  let total = 0;
  const walk = async (d) => {
    for (const e of await readdir(d, { withFileTypes: true })) {
      if (e.isDirectory()) await walk(join(d, e.name));
      else total++;
    }
  };
  await walk(dir);
  return total;
};

const cleanDir = async (target) => {
  if (!(await exists(target))) return;
  for (const entry of await readdir(target, { withFileTypes: true })) {
    if (entry.name === '.git' || entry.name === '.gitkeep') continue;
    await rm(join(target, entry.name), { recursive: true, force: true });
  }
};

const syncTo = async (target) => {
  await cleanDir(target);
  await cp(SRC, target, {
    recursive: true,
    filter: (src) => !src.endsWith('/.DS_Store'),
  });
  return countFiles(target);
};

const runStep = (label, cmd, env = {}) => {
  console.log(`\n▶ ${label}`);
  execSync(cmd, {
    cwd: ROOT,
    stdio: 'inherit',
    env: { ...process.env, ...env },
  });
};

const overrideRobotsForPreprod = async () => {
  const robotsPath = join(TARGET_NEW, 'robots.txt');
  const content = [
    '# new.panprstenu.cz — PREPROD / staging',
    `# Generated by build-deploy.mjs @ ${new Date().toISOString()}`,
    '',
    'User-agent: *',
    'Disallow: /',
    '',
    '# Tato verze webu slouží jen pro interní testy a nesmí být indexována',
    '# vyhledávači. LIVE production běží na https://www.panprstenu.cz/.',
    '',
  ].join('\n');
  await writeFile(robotsPath, content, 'utf-8');
  console.log(`  ✓ robots.txt přepsán pro preprod (Disallow: /)`);
};

const main = async () => {
  const startedAt = Date.now();

  // 1) Prebuild — translation-status + llms (běží jednou, výsledky platí pro oba buildy)
  runStep('Prebuild: translation-status', 'node scripts/translation-status.mjs');
  runStep('Prebuild: generate-llms', 'node scripts/generate-llms.mjs');

  // 2) Build pro LIVE (bez PUBLIC_NOINDEX)
  runStep('Build LIVE (bez noindex)', 'npx astro build', { PUBLIC_NOINDEX: '' });
  const liveCount = await syncTo(TARGET_LIVE);
  console.log(`  ✓ public_html/: ${liveCount.toLocaleString()} souborů`);

  // 3) Build pro NEW (PUBLIC_NOINDEX=true)
  runStep('Build NEW preprod (PUBLIC_NOINDEX=true)', 'npx astro build', { PUBLIC_NOINDEX: 'true' });
  const newCount = await syncTo(TARGET_NEW);
  console.log(`  ✓ public_html_new/: ${newCount.toLocaleString()} souborů`);

  // 4) Přepsat robots.txt na zákaz indexace pro NEW
  await overrideRobotsForPreprod();

  const elapsed = ((Date.now() - startedAt) / 1000).toFixed(1);
  console.log(`\n✓ Build deploy completed in ${elapsed}s`);
  console.log(`  LIVE: public_html/ (${liveCount} souborů, indexovatelné)`);
  console.log(`  NEW : public_html_new/ (${newCount} souborů, noindex + Disallow: /)`);
};

main().catch((e) => {
  console.error('\n✗ build-deploy failed:', e.message);
  process.exit(1);
});
